var loadRes = [
    //"res/Landlords/item/num.png",
    "res/new_hall/icon/bean0.png",
    "res/new_hall/icon/bean2.png",
    "res/shop/coin.png",
    "res/shop/bean.png",
    "res/shop/num2.png",
    "res/shop/cny.png",
    "res/new_hall/game_shared/animation/chuntian/skeleton.json",
    "res/new_hall/game_shared/animation/chuntian/skeleton.atlas",
    "res/new_hall/game_shared/animation/chuntian/skeleton.png",
    "res/new_hall/game_shared/animation/bomb/skeleton.json",
    "res/new_hall/game_shared/animation/bomb/skeleton.atlas",
    "res/new_hall/game_shared/animation/bomb/skeleton.png",
    "res/new_hall/game_shared/animation/feiji/skeleton.json",
    "res/new_hall/game_shared/animation/feiji/skeleton.atlas",
    "res/new_hall/game_shared/animation/feiji/skeleton.png",
    "res/new_hall/game_shared/animation/huojian/skeleton.json",
    "res/new_hall/game_shared/animation/huojian/skeleton.atlas",
    "res/new_hall/game_shared/animation/huojian/skeleton.png",
    "res/new_hall/game_shared/animation/kanggong/skeleton.json",
    "res/new_hall/game_shared/animation/kanggong/skeleton.atlas",
    "res/new_hall/game_shared/animation/kanggong/skeleton.png",
    "res/new_hall/game_shared/animation/shunzi/skeleton.json",
    "res/new_hall/game_shared/animation/shunzi/skeleton.atlas",
    "res/new_hall/game_shared/animation/shunzi/skeleton.png",
    "res/new_hall/game_shared/animation/biaoqing/skeleton.json",
    "res/new_hall/game_shared/animation/biaoqing/skeleton.atlas",
    "res/new_hall/game_shared/animation/biaoqing/skeleton.png",
    "res/spine/interactItem/banzhuan/skeleton.json",
    "res/spine/interactItem/banzhuan/skeleton.atlas",
    "res/spine/interactItem/banzhuan/skeleton.png",
    "res/spine/interactItem/xianhua/skeleton.json",
    "res/spine/interactItem/xianhua/skeleton.atlas",
    "res/spine/interactItem/xianhua/skeleton.png",
    "res/spine/interactItem/zhadan/skeleton.json",
    "res/spine/interactItem/zhadan/skeleton.atlas",
    "res/spine/interactItem/zhadan/skeleton.png"
];

//common
var g_mapCommonRes = {
    end_particle_plist:"res/particle/end_particle.plist",
    end_particle_png:"res/particle/end_particle.png",
    particle_plist:"res/particle/particleeffects.plist",
    particle_png:"res/particle/particleeffects.png",
    roleparticle_plist:"res/particle/roleparticle.plist",
    roleparticle_png:"res/particle/roleparticle.png",
    small_coin_png:"res/small_icon/small_coin.png",
    small_bean_png:"res/small_icon/small_bean.png",
    small_item1_png:"res/small_icon/small_item1.png",
    LLcard_plist:"res/new_hall/card/big_card.plist",
    LLcard_png:"res/new_hall/card/big_card.png"

}

//GD
var g_mapGDRes = {
    card_plist:"res/plist/card.plist",
    card_png:"res/plist/card.png",
    vip_card_plist:"res/plist/vip_card.plist",
    vip_card_png:"res/plist/vip_card.png",
    small_card_plist:"res/plist/small_card.plist",
    small_card_png:"res/plist/small_card.png",

    chat_plist:"res/plist/chat.plist",
    chat_png:"res/plist/chat.png"
};

//audio
var g_mapAudio = {}
if (cc.sys.os == cc.sys.OS_IOS) {
    g_mapAudio = {
        back:"res/sound/back.mp3",                  //背景
        button:"res/sound/iOS/button.wav",              //按钮
        card:"res/sound/iOS/card.wav",                  //牌
        bomb:"res/sound/iOS/bomb.wav",
        rocket:"res/sound/iOS/rocket.wav",
        bomb_king:"res/sound/iOS/bomb_king.wav",
        plane:"res/sound/iOS/plane.wav",
        quarte:"res/sound/iOS/quarte.wav",
        warn:"res/sound/iOS/warn.wav",
        rank:"res/sound/iOS/rank.wav",
        lost:"res/sound/iOS/lost.wav",
        win:"res/sound/iOS/win.wav",
        countdown:"res/sound/iOS/countdown.wav",
        turn:"res/sound/iOS/turn.wav",
        fly_card:"res/sound/iOS/fly_card.wav",
        //男
        m_bigCard_0: "res/sound/iOS/man/bigCard_0.wav",
        m_bigCard_1: "res/sound/iOS/man/bigCard_1.wav",
        m_bomb: "res/sound/iOS/man/bomb.wav",
        m_bomb_king: "res/sound/iOS/man/bomb_king.wav",
        m_linkPair_0: "res/sound/iOS/man/linkPair_0.wav",
        m_linkPair_1: "res/sound/iOS/man/linkPair_1.wav",
        m_one_2: "res/sound/iOS/man/one_2.wav",
        m_one_3: "res/sound/iOS/man/one_3.wav",
        m_one_4: "res/sound/iOS/man/one_4.wav",
        m_one_5: "res/sound/iOS/man/one_5.wav",
        m_one_6: "res/sound/iOS/man/one_6.wav",
        m_one_7: "res/sound/iOS/man/one_7.wav",
        m_one_8: "res/sound/iOS/man/one_8.wav",
        m_one_9: "res/sound/iOS/man/one_9.wav",
        m_one_10: "res/sound/iOS/man/one_10.wav",
        m_one_J: "res/sound/iOS/man/one_J.wav",
        m_one_Q: "res/sound/iOS/man/one_Q.wav",
        m_one_K: "res/sound/iOS/man/one_K.wav",
        m_one_A: "res/sound/iOS/man/one_A.wav",
        m_one_min: "res/sound/iOS/man/one_min.wav",
        m_one_max: "res/sound/iOS/man/one_max.wav",
        m_pair_2: "res/sound/iOS/man/pair_2.wav",
        m_pair_3: "res/sound/iOS/man/pair_3.wav",
        m_pair_4: "res/sound/iOS/man/pair_4.wav",
        m_pair_5: "res/sound/iOS/man/pair_5.wav",
        m_pair_6: "res/sound/iOS/man/pair_6.wav",
        m_pair_7: "res/sound/iOS/man/pair_7.wav",
        m_pair_8: "res/sound/iOS/man/pair_8.wav",
        m_pair_9: "res/sound/iOS/man/pair_9.wav",
        m_pair_10: "res/sound/iOS/man/pair_10.wav",
        m_pair_J: "res/sound/iOS/man/pair_J.wav",
        m_pair_Q: "res/sound/iOS/man/pair_Q.wav",
        m_pair_K: "res/sound/iOS/man/pair_K.wav",
        m_pair_A: "res/sound/iOS/man/pair_A.wav",
        m_pair_min: "res/sound/iOS/man/pair_min.wav",
        m_pair_max: "res/sound/iOS/man/pair_max.wav",
        m_pass_0: "res/sound/iOS/man/pass_0.wav",
        m_pass_1: "res/sound/iOS/man/pass_1.wav",
        m_pass_2: "res/sound/iOS/man/pass_2.wav",
        m_pass_3: "res/sound/iOS/man/pass_3.wav",
        m_quarte: "res/sound/iOS/man/quarte.wav",
        m_quarte_max: "res/sound/iOS/man/quarte_max.wav",
        m_rocket_0: "res/sound/iOS/man/rocket_0.wav",
        m_rocket_1: "res/sound/iOS/man/rocket_1.wav",
        m_sequence: "res/sound/iOS/man/sequence.wav",
        m_three_0: "res/sound/iOS/man/three_0.wav",
        m_three_1: "res/sound/iOS/man/three_1.wav",
        m_threeSequence: "res/sound/iOS/man/threeSequence.wav",
        m_threeTwo_0: "res/sound/iOS/man/threeTwo_0.wav",
        m_threeTwo_1: "res/sound/iOS/man/threeTwo_1.wav",
        //女
        w_bigCard_0: "res/sound/iOS/woman/bigCard_0.wav",
        w_bigCard_1: "res/sound/iOS/woman/bigCard_1.wav",
        w_bomb: "res/sound/iOS/woman/bomb.wav",
        w_bomb_king: "res/sound/iOS/woman/bomb_king.wav",
        w_linkPair_0: "res/sound/iOS/woman/linkPair_0.wav",
        w_linkPair_1: "res/sound/iOS/woman/linkPair_1.wav",
        w_one_2: "res/sound/iOS/woman/one_2.wav",
        w_one_3: "res/sound/iOS/woman/one_3.wav",
        w_one_4: "res/sound/iOS/woman/one_4.wav",
        w_one_5: "res/sound/iOS/woman/one_5.wav",
        w_one_6: "res/sound/iOS/woman/one_6.wav",
        w_one_7: "res/sound/iOS/woman/one_7.wav",
        w_one_8: "res/sound/iOS/woman/one_8.wav",
        w_one_9: "res/sound/iOS/woman/one_9.wav",
        w_one_10: "res/sound/iOS/woman/one_10.wav",
        w_one_J: "res/sound/iOS/woman/one_J.wav",
        w_one_Q: "res/sound/iOS/woman/one_Q.wav",
        w_one_K: "res/sound/iOS/woman/one_K.wav",
        w_one_A: "res/sound/iOS/woman/one_A.wav",
        w_one_min: "res/sound/iOS/woman/one_min.wav",
        w_one_max: "res/sound/iOS/woman/one_max.wav",
        w_pair_2: "res/sound/iOS/woman/pair_2.wav",
        w_pair_3: "res/sound/iOS/woman/pair_3.wav",
        w_pair_4: "res/sound/iOS/woman/pair_4.wav",
        w_pair_5: "res/sound/iOS/woman/pair_5.wav",
        w_pair_6: "res/sound/iOS/woman/pair_6.wav",
        w_pair_7: "res/sound/iOS/woman/pair_7.wav",
        w_pair_8: "res/sound/iOS/woman/pair_8.wav",
        w_pair_9: "res/sound/iOS/woman/pair_9.wav",
        w_pair_10: "res/sound/iOS/woman/pair_10.wav",
        w_pair_J: "res/sound/iOS/woman/pair_J.wav",
        w_pair_Q: "res/sound/iOS/woman/pair_Q.wav",
        w_pair_K: "res/sound/iOS/woman/pair_K.wav",
        w_pair_A: "res/sound/iOS/woman/pair_A.wav",
        w_pair_min: "res/sound/iOS/woman/pair_min.wav",
        w_pair_max: "res/sound/iOS/woman/pair_max.wav",
        w_pass_0: "res/sound/iOS/woman/pass_0.wav",
        w_pass_1: "res/sound/iOS/woman/pass_1.wav",
        w_pass_2: "res/sound/iOS/woman/pass_2.wav",
        w_pass_3: "res/sound/iOS/woman/pass_3.wav",
        w_quarte: "res/sound/iOS/woman/quarte.wav",
        w_quarte_max: "res/sound/iOS/woman/quarte_max.wav",
        w_rocket_0: "res/sound/iOS/woman/rocket_0.wav",
        w_rocket_1: "res/sound/iOS/woman/rocket_1.wav",
        w_sequence: "res/sound/iOS/woman/sequence.wav",
        w_three_0: "res/sound/iOS/woman/three_0.wav",
        w_three_1: "res/sound/iOS/woman/three_1.wav",
        w_threeSequence: "res/sound/iOS/woman/threeSequence.wav",
        w_threeTwo_0: "res/sound/iOS/woman/threeTwo_0.wav",
        w_threeTwo_1: "res/sound/iOS/woman/threeTwo_1.wav",
        w_Gold_1: "res/sound/iOS/glod_1.wav",

        //LL
        S_DispatchCard:"res/sound/shared/ios/system/DispatchCard.wav",
        S_OutCard:"res/sound/shared/ios/system/OutCard.wav",
        S_LOST:"res/sound/shared/ios/effect/LOST.wav",
        S_Plane:"res/sound/shared/ios/effect/Plane.wav",
        S_S_line:"res/sound/shared/ios/effect/S_line.wav",
        S_set_warn:"res/sound/shared/ios/effect/set_warn.wav",
        S_WIN:"res/sound/shared/ios/effect/WIN_0.wav",
        //LL_back:"res/sound/LL/ios/system/BGMusic.wav",
        LL_back:"res/sound/shared/BGMusic.mp3",
        LL_fanbei:"res/sound/LL/ios/effect/fanbei.wav",
        LL_Spring:"res/sound/LL/ios/effect/Spring.wav",
        LL_M_baojing1:"res/sound/LL/ios/man/baojing1.wav",
        LL_M_baojing2:"res/sound/LL/ios/man/baojing2.wav",
        LL_M_bujiabei:"res/sound/LL/ios/man/bujiabei.wav",
        LL_M_D_Line_M:"res/sound/LL/ios/man/D_Line_M.wav",
        LL_M_dan_M_01:"res/sound/LL/ios/man/dan_M_01.wav",
        LL_M_dan_M_02:"res/sound/LL/ios/man/dan_M_02.wav",
        LL_M_dan_M_03:"res/sound/LL/ios/man/dan_M_03.wav",
        LL_M_dan_M_04:"res/sound/LL/ios/man/dan_M_04.wav",
        LL_M_dan_M_05:"res/sound/LL/ios/man/dan_M_05.wav",
        LL_M_dan_M_06:"res/sound/LL/ios/man/dan_M_06.wav",
        LL_M_dan_M_07:"res/sound/LL/ios/man/dan_M_07.wav",
        LL_M_dan_M_08:"res/sound/LL/ios/man/dan_M_08.wav",
        LL_M_dan_M_09:"res/sound/LL/ios/man/dan_M_09.wav",
        LL_M_dan_M_10:"res/sound/LL/ios/man/dan_M_10.wav",
        LL_M_dan_M_11:"res/sound/LL/ios/man/dan_M_11.wav",
        LL_M_dan_M_12:"res/sound/LL/ios/man/dan_M_12.wav",
        LL_M_dan_M_13:"res/sound/LL/ios/man/dan_M_13.wav",
        LL_M_dan_M_14:"res/sound/LL/ios/man/dan_M_14.wav",
        LL_M_dan_M_15:"res/sound/LL/ios/man/dan_M_15.wav",
        LL_M_dani1:"res/sound/LL/ios/man/dani1.wav",
        LL_M_dani2:"res/sound/LL/ios/man/dani2.wav",
        LL_M_dani3:"res/sound/LL/ios/man/dani3.wav",
        LL_M_dui_M_01:"res/sound/LL/ios/man/dui_M_01.wav",
        LL_M_dui_M_02:"res/sound/LL/ios/man/dui_M_02.wav",
        LL_M_dui_M_03:"res/sound/LL/ios/man/dui_M_03.wav",
        LL_M_dui_M_04:"res/sound/LL/ios/man/dui_M_04.wav",
        LL_M_dui_M_05:"res/sound/LL/ios/man/dui_M_05.wav",
        LL_M_dui_M_06:"res/sound/LL/ios/man/dui_M_06.wav",
        LL_M_dui_M_07:"res/sound/LL/ios/man/dui_M_07.wav",
        LL_M_dui_M_08:"res/sound/LL/ios/man/dui_M_08.wav",
        LL_M_dui_M_09:"res/sound/LL/ios/man/dui_M_09.wav",
        LL_M_dui_M_10:"res/sound/LL/ios/man/dui_M_10.wav",
        LL_M_dui_M_11:"res/sound/LL/ios/man/dui_M_11.wav",
        LL_M_dui_M_12:"res/sound/LL/ios/man/dui_M_12.wav",
        LL_M_dui_M_13:"res/sound/LL/ios/man/dui_M_13.wav",
        LL_M_jiabei:"res/sound/LL/ios/man/jiabei.wav",
        LL_M_Pass_M_01:"res/sound/LL/ios/man/Pass_M_01.wav",
        LL_M_Pass_M_02:"res/sound/LL/ios/man/Pass_M_02.wav",
        LL_M_Pass_M_03:"res/sound/LL/ios/man/Pass_M_03.wav",
        LL_M_Pass_M_04:"res/sound/LL/ios/man/Pass_M_04.wav",
        LL_M_Plane_M:"res/sound/LL/ios/man/Plane_M.wav",
        LL_M_S_Line_M:"res/sound/LL/ios/man/S_Line_M.wav",
        LL_M_sandaiyi:"res/sound/LL/ios/man/sandaiyi.wav",
        LL_M_sandaiyidui:"res/sound/LL/ios/man/sandaiyidui.wav",
        LL_M_sidaier:"res/sound/LL/ios/man/sidaier.wav",
        LL_M_sidailiangdui:"res/sound/LL/ios/man/sidailiangdui.wav",
        LL_M_T_Line_M:"res/sound/LL/ios/man/T_Line_M.wav",
        LL_M_Three_M:"res/sound/LL/ios/man/Three_M.wav",
        LL_M_Three2_M:"res/sound/LL/ios/man/Three2_M.wav",
        LL_M_wangzha:"res/sound/LL/ios/man/wangzha.wav",
        LL_M_zhadan:"res/sound/LL/ios/man/zhadan.wav",
        LL_M_bujiao:"res/sound/LL/ios/man/bujiao.wav",
        LL_M_buqiang:"res/sound/LL/ios/man/buqiang.wav",
        LL_M_jiaodizhu:"res/sound/LL/ios/man/jiaodizhu.wav",
        LL_M_mingpai:"res/sound/LL/ios/man/mingpai.wav",
        LL_M_qiangdizhu0:"res/sound/LL/ios/man/qiangdizhu0.wav",
        LL_M_qiangdizhu1:"res/sound/LL/ios/man/qiangdizhu1.wav",
        LL_M_qiangdizhu2:"res/sound/LL/ios/man/qiangdizhu2.wav",
        LL_M_sanzhang:"res/sound/LL/ios/man/triple_b.wav",
        LL_F_baojing1:"res/sound/LL/ios/female/baojing1.wav",
        LL_F_baojing2:"res/sound/LL/ios/female/baojing2.wav",
        LL_F_bujiabei:"res/sound/LL/ios/female/bujiabei.wav",
        LL_F_D_Line_F:"res/sound/LL/ios/female/D_Line_F.wav",
        LL_F_bujiao:"res/sound/LL/ios/female/bujiao.wav",
        LL_F_buqiang:"res/sound/LL/ios/female/buqiang.wav",
        LL_F_dan_F_01:"res/sound/LL/ios/female/dan_F_01.wav",
        LL_F_dan_F_02:"res/sound/LL/ios/female/dan_F_02.wav",
        LL_F_dan_F_03:"res/sound/LL/ios/female/dan_F_03.wav",
        LL_F_dan_F_04:"res/sound/LL/ios/female/dan_F_04.wav",
        LL_F_dan_F_05:"res/sound/LL/ios/female/dan_F_05.wav",
        LL_F_dan_F_06:"res/sound/LL/ios/female/dan_F_06.wav",
        LL_F_dan_F_07:"res/sound/LL/ios/female/dan_F_07.wav",
        LL_F_dan_F_08:"res/sound/LL/ios/female/dan_F_08.wav",
        LL_F_dan_F_09:"res/sound/LL/ios/female/dan_F_09.wav",
        LL_F_dan_F_10:"res/sound/LL/ios/female/dan_F_10.wav",
        LL_F_dan_F_11:"res/sound/LL/ios/female/dan_F_11.wav",
        LL_F_dan_F_12:"res/sound/LL/ios/female/dan_F_12.wav",
        LL_F_dan_F_13:"res/sound/LL/ios/female/dan_F_13.wav",
        LL_F_dan_F_14:"res/sound/LL/ios/female/dan_F_14.wav",
        LL_F_dan_F_15:"res/sound/LL/ios/female/dan_F_15.wav",

        LL_F_dani1:"res/sound/LL/ios/female/dani1.wav",
        LL_F_dani2:"res/sound/LL/ios/female/dani2.wav",
        LL_F_dani3:"res/sound/LL/ios/female/dani3.wav",
        LL_F_dui_F_01:"res/sound/LL/ios/female/dui_F_01.wav",
        LL_F_dui_F_02:"res/sound/LL/ios/female/dui_F_02.wav",
        LL_F_dui_F_03:"res/sound/LL/ios/female/dui_F_03.wav",
        LL_F_dui_F_04:"res/sound/LL/ios/female/dui_F_04.wav",
        LL_F_dui_F_05:"res/sound/LL/ios/female/dui_F_05.wav",
        LL_F_dui_F_06:"res/sound/LL/ios/female/dui_F_06.wav",
        LL_F_dui_F_07:"res/sound/LL/ios/female/dui_F_07.wav",
        LL_F_dui_F_08:"res/sound/LL/ios/female/dui_F_08.wav",
        LL_F_dui_F_09:"res/sound/LL/ios/female/dui_F_09.wav",
        LL_F_dui_F_10:"res/sound/LL/ios/female/dui_F_10.wav",
        LL_F_dui_F_11:"res/sound/LL/ios/female/dui_F_11.wav",
        LL_F_dui_F_12:"res/sound/LL/ios/female/dui_F_12.wav",
        LL_F_dui_F_13:"res/sound/LL/ios/female/dui_F_13.wav",
        LL_F_jiabei:"res/sound/LL/ios/female/jiabei.wav",
        LL_F_jiaodizhu:"res/sound/LL/ios/female/jiaodizhu.wav",
        LL_F_mingpai:"res/sound/LL/ios/female/mingpai.wav",
        LL_F_Pass_F_01:"res/sound/LL/ios/female/Pass_F_01.wav",
        LL_F_Pass_F_02:"res/sound/LL/ios/female/Pass_F_02.wav",
        LL_F_Pass_F_03:"res/sound/LL/ios/female/Pass_F_03.wav",
        LL_F_Pass_F_04:"res/sound/LL/ios/female/Pass_F_04.wav",
        LL_F_Plane_F:"res/sound/LL/ios/female/Plane_F.wav",
        LL_F_qiangdizhu0:"res/sound/LL/ios/female/qiangdizhu0.wav",
        LL_F_qiangdizhu1:"res/sound/LL/ios/female/qiangdizhu1.wav",
        LL_F_qiangdizhu2:"res/sound/LL/ios/female/qiangdizhu2.wav",
        LL_F_S_Line_F:"res/sound/LL/ios/female/S_Line_F.wav",
        LL_F_sandaiyi:"res/sound/LL/ios/female/sandaiyi.wav",
        LL_F_sandaiyidui:"res/sound/LL/ios/female/sandaiyidui.wav",
        LL_F_sidaier:"res/sound/LL/ios/female/sidaier.wav",
        LL_F_sidailiangdui:"res/sound/LL/ios/female/sidailiangdui.wav",
        LL_F_superdouble:"res/sound/LL/ios/female/superdouble.wav",
        LL_F_T_Line_F:"res/sound/LL/ios/female/T_Line_F.wav",
        //LL_F_Three_M:"res/sound/LL/ios/female/Three_M.wav",
        //LL_F_Three2_M:"res/sound/LL/ios/female/Three2_M.wav",
        LL_F_wangzha:"res/sound/LL/ios/female/wangzha.wav",
        LL_F_zhadan:"res/sound/LL/ios/female/zhadan.wav",
        LL_F_sanzhang:"res/sound/LL/ios/female/triple_0_g.wav"


    }
}
else
{
    g_mapAudio = {
        back:"res/sound/back.mp3",                  //背景
        button:"res/sound/android/button.ogg",              //按钮
        card:"res/sound/android/card.ogg",                  //牌
        bomb:"res/sound/android/bomb.ogg",
        rocket:"res/sound/android/rocket.ogg",
        bomb_king:"res/sound/android/bomb_king.ogg",
        plane:"res/sound/android/plane.ogg",
        quarte:"res/sound/android/quarte.ogg",
        warn:"res/sound/android/warn.ogg",
        rank:"res/sound/android/rank.ogg",
        lost:"res/sound/android/lost.ogg",
        win:"res/sound/android/win.ogg",
        countdown:"res/sound/android/countdown.ogg",
        turn:"res/sound/android/turn.ogg",
        fly_card:"res/sound/android/fly_card.ogg",
        //男
        m_bigCard_0: "res/sound/android/man/bigCard_0.ogg",
        m_bigCard_1: "res/sound/android/man/bigCard_1.ogg",
        m_bomb: "res/sound/android/man/bomb.ogg",
        m_bomb_king: "res/sound/android/man/bomb_king.ogg",
        m_linkPair_0: "res/sound/android/man/linkPair_0.ogg",
        m_linkPair_1: "res/sound/android/man/linkPair_1.ogg",
        m_one_2: "res/sound/android/man/one_2.ogg",
        m_one_3: "res/sound/android/man/one_3.ogg",
        m_one_4: "res/sound/android/man/one_4.ogg",
        m_one_5: "res/sound/android/man/one_5.ogg",
        m_one_6: "res/sound/android/man/one_6.ogg",
        m_one_7: "res/sound/android/man/one_7.ogg",
        m_one_8: "res/sound/android/man/one_8.ogg",
        m_one_9: "res/sound/android/man/one_9.ogg",
        m_one_10: "res/sound/android/man/one_10.ogg",
        m_one_J: "res/sound/android/man/one_J.ogg",
        m_one_Q: "res/sound/android/man/one_Q.ogg",
        m_one_K: "res/sound/android/man/one_K.ogg",
        m_one_A: "res/sound/android/man/one_A.ogg",
        m_one_min: "res/sound/android/man/one_min.ogg",
        m_one_max: "res/sound/android/man/one_max.ogg",
        m_pair_2: "res/sound/android/man/pair_2.ogg",
        m_pair_3: "res/sound/android/man/pair_3.ogg",
        m_pair_4: "res/sound/android/man/pair_4.ogg",
        m_pair_5: "res/sound/android/man/pair_5.ogg",
        m_pair_6: "res/sound/android/man/pair_6.ogg",
        m_pair_7: "res/sound/android/man/pair_7.ogg",
        m_pair_8: "res/sound/android/man/pair_8.ogg",
        m_pair_9: "res/sound/android/man/pair_9.ogg",
        m_pair_10: "res/sound/android/man/pair_10.ogg",
        m_pair_J: "res/sound/android/man/pair_J.ogg",
        m_pair_Q: "res/sound/android/man/pair_Q.ogg",
        m_pair_K: "res/sound/android/man/pair_K.ogg",
        m_pair_A: "res/sound/android/man/pair_A.ogg",
        m_pair_min: "res/sound/android/man/pair_min.ogg",
        m_pair_max: "res/sound/android/man/pair_max.ogg",
        m_pass_0: "res/sound/android/man/pass_0.ogg",
        m_pass_1: "res/sound/android/man/pass_1.ogg",
        m_pass_2: "res/sound/android/man/pass_2.ogg",
        m_pass_3: "res/sound/android/man/pass_3.ogg",
        m_quarte: "res/sound/android/man/quarte.ogg",
        m_quarte_max: "res/sound/android/man/quarte_max.ogg",
        m_rocket_0: "res/sound/android/man/rocket_0.ogg",
        m_rocket_1: "res/sound/android/man/rocket_1.ogg",
        m_sequence: "res/sound/android/man/sequence.ogg",
        m_three_0: "res/sound/android/man/three_0.ogg",
        m_three_1: "res/sound/android/man/three_1.ogg",
        m_threeSequence: "res/sound/android/man/threeSequence.ogg",
        m_threeTwo_0: "res/sound/android/man/threeTwo_0.ogg",
        m_threeTwo_1: "res/sound/android/man/threeTwo_1.ogg",
        //女
        w_bigCard_0: "res/sound/android/woman/bigCard_0.ogg",
        w_bigCard_1: "res/sound/android/woman/bigCard_1.ogg",
        w_bomb: "res/sound/android/woman/bomb.ogg",
        w_bomb_king: "res/sound/android/woman/bomb_king.ogg",
        w_linkPair_0: "res/sound/android/woman/linkPair_0.ogg",
        w_linkPair_1: "res/sound/android/woman/linkPair_1.ogg",
        w_one_2: "res/sound/android/woman/one_2.ogg",
        w_one_3: "res/sound/android/woman/one_3.ogg",
        w_one_4: "res/sound/android/woman/one_4.ogg",
        w_one_5: "res/sound/android/woman/one_5.ogg",
        w_one_6: "res/sound/android/woman/one_6.ogg",
        w_one_7: "res/sound/android/woman/one_7.ogg",
        w_one_8: "res/sound/android/woman/one_8.ogg",
        w_one_9: "res/sound/android/woman/one_9.ogg",
        w_one_10: "res/sound/android/woman/one_10.ogg",
        w_one_J: "res/sound/android/woman/one_J.ogg",
        w_one_Q: "res/sound/android/woman/one_Q.ogg",
        w_one_K: "res/sound/android/woman/one_K.ogg",
        w_one_A: "res/sound/android/woman/one_A.ogg",
        w_one_min: "res/sound/android/woman/one_min.ogg",
        w_one_max: "res/sound/android/woman/one_max.ogg",
        w_pair_2: "res/sound/android/woman/pair_2.ogg",
        w_pair_3: "res/sound/android/woman/pair_3.ogg",
        w_pair_4: "res/sound/android/woman/pair_4.ogg",
        w_pair_5: "res/sound/android/woman/pair_5.ogg",
        w_pair_6: "res/sound/android/woman/pair_6.ogg",
        w_pair_7: "res/sound/android/woman/pair_7.ogg",
        w_pair_8: "res/sound/android/woman/pair_8.ogg",
        w_pair_9: "res/sound/android/woman/pair_9.ogg",
        w_pair_10: "res/sound/android/woman/pair_10.ogg",
        w_pair_J: "res/sound/android/woman/pair_J.ogg",
        w_pair_Q: "res/sound/android/woman/pair_Q.ogg",
        w_pair_K: "res/sound/android/woman/pair_K.ogg",
        w_pair_A: "res/sound/android/woman/pair_A.ogg",
        w_pair_min: "res/sound/android/woman/pair_min.ogg",
        w_pair_max: "res/sound/android/woman/pair_max.ogg",
        w_pass_0: "res/sound/android/woman/pass_0.ogg",
        w_pass_1: "res/sound/android/woman/pass_1.ogg",
        w_pass_2: "res/sound/android/woman/pass_2.ogg",
        w_pass_3: "res/sound/android/woman/pass_3.ogg",
        w_quarte: "res/sound/android/woman/quarte.ogg",
        w_quarte_max: "res/sound/android/woman/quarte_max.ogg",
        w_rocket_0: "res/sound/android/woman/rocket_0.ogg",
        w_rocket_1: "res/sound/android/woman/rocket_1.ogg",
        w_sequence: "res/sound/android/woman/sequence.ogg",
        w_three_0: "res/sound/android/woman/three_0.ogg",
        w_three_1: "res/sound/android/woman/three_1.ogg",
        w_threeSequence: "res/sound/android/woman/threeSequence.ogg",
        w_threeTwo_0: "res/sound/android/woman/threeTwo_0.ogg",
        w_threeTwo_1: "res/sound/android/woman/threeTwo_1.ogg",
        w_Gold_1:"res/sound/android/glod_1.ogg",


        //LL
        S_DispatchCard:"res/sound/shared/android/system/DispatchCard.ogg",
        S_GameStart:"res/sound/shared/android/system/GameStart.ogg",
        S_GameWarn:"res/sound/shared/android/system/GameWarn.ogg",
        S_naozong:"res/sound/shared/android/system/naozong.ogg",
        S_OutCard:"res/sound/shared/android/system/OutCard.ogg",
        S_Bomb:"res/sound/shared/android/effect/Bomb.ogg",
        S_D_Line:"res/sound/shared/android/effect/D_Line.ogg",
        S_K_Bomb:"res/sound/shared/android/effect/K_Bomb.ogg",
        S_LOST:"res/sound/shared/android/effect/LOST.ogg",
        S_Plane:"res/sound/shared/android/effect/Plane.ogg",
        S_S_line:"res/sound/shared/android/effect/S_line.ogg",
        S_set_warn:"res/sound/shared/android/effect/set_warn.ogg",
        S_WIN:"res/sound/shared/android/effect/WIN_0.ogg",
        //LL_back:"res/sound/LL/android/system/BGMusic.ogg",
        LL_back:"res/sound/shared/BGMusic.mp3",
        LL_fanbei:"res/sound/LL/android/effect/fanbei.ogg",
        LL_Spring:"res/sound/LL/android/effect/Spring.ogg",
        LL_M_baojing1:"res/sound/LL/android/man/baojing1.ogg",
        LL_M_baojing2:"res/sound/LL/android/man/baojing2.ogg",
        LL_M_bujiabei:"res/sound/LL/android/man/bujiabei.ogg",
        LL_M_D_Line_M:"res/sound/LL/android/man/D_Line_M.ogg",
        LL_M_dan_M_01:"res/sound/LL/android/man/dan_M_01.ogg",
        LL_M_dan_M_02:"res/sound/LL/android/man/dan_M_02.ogg",
        LL_M_dan_M_03:"res/sound/LL/android/man/dan_M_03.ogg",
        LL_M_dan_M_04:"res/sound/LL/android/man/dan_M_04.ogg",
        LL_M_dan_M_05:"res/sound/LL/android/man/dan_M_05.ogg",
        LL_M_dan_M_06:"res/sound/LL/android/man/dan_M_06.ogg",
        LL_M_dan_M_07:"res/sound/LL/android/man/dan_M_07.ogg",
        LL_M_dan_M_08:"res/sound/LL/android/man/dan_M_08.ogg",
        LL_M_dan_M_09:"res/sound/LL/android/man/dan_M_09.ogg",
        LL_M_dan_M_10:"res/sound/LL/android/man/dan_M_10.ogg",
        LL_M_dan_M_11:"res/sound/LL/android/man/dan_M_11.ogg",
        LL_M_dan_M_12:"res/sound/LL/android/man/dan_M_12.ogg",
        LL_M_dan_M_13:"res/sound/LL/android/man/dan_M_13.ogg",
        LL_M_dan_M_14:"res/sound/LL/android/man/dan_M_14.ogg",
        LL_M_dan_M_15:"res/sound/LL/android/man/dan_M_15.ogg",
        LL_M_dani1:"res/sound/LL/android/man/dani1.ogg",
        LL_M_dani2:"res/sound/LL/android/man/dani2.ogg",
        LL_M_dani3:"res/sound/LL/android/man/dani3.ogg",
        LL_M_dui_M_01:"res/sound/LL/android/man/dui_M_01.ogg",
        LL_M_dui_M_02:"res/sound/LL/android/man/dui_M_02.ogg",
        LL_M_dui_M_03:"res/sound/LL/android/man/dui_M_03.ogg",
        LL_M_dui_M_04:"res/sound/LL/android/man/dui_M_04.ogg",
        LL_M_dui_M_05:"res/sound/LL/android/man/dui_M_05.ogg",
        LL_M_dui_M_06:"res/sound/LL/android/man/dui_M_06.ogg",
        LL_M_dui_M_07:"res/sound/LL/android/man/dui_M_07.ogg",
        LL_M_dui_M_08:"res/sound/LL/android/man/dui_M_08.ogg",
        LL_M_dui_M_09:"res/sound/LL/android/man/dui_M_09.ogg",
        LL_M_dui_M_10:"res/sound/LL/android/man/dui_M_10.ogg",
        LL_M_dui_M_11:"res/sound/LL/android/man/dui_M_11.ogg",
        LL_M_dui_M_12:"res/sound/LL/android/man/dui_M_12.ogg",
        LL_M_dui_M_13:"res/sound/LL/android/man/dui_M_13.ogg",
        LL_M_jiabei:"res/sound/LL/android/man/jiabei.ogg",
        LL_M_Pass_M_01:"res/sound/LL/android/man/Pass_M_01.ogg",
        LL_M_Pass_M_02:"res/sound/LL/android/man/Pass_M_02.ogg",
        LL_M_Pass_M_03:"res/sound/LL/android/man/Pass_M_03.ogg",
        LL_M_Pass_M_04:"res/sound/LL/android/man/Pass_M_04.ogg",
        LL_M_Plane_M:"res/sound/LL/android/man/Plane_M.ogg",
        LL_M_S_Line_M:"res/sound/LL/android/man/S_Line_M.ogg",
        LL_M_sandaiyi:"res/sound/LL/android/man/sandaiyi.ogg",
        LL_M_sandaiyidui:"res/sound/LL/android/man/sandaiyidui.ogg",
        LL_M_sidaier:"res/sound/LL/android/man/sidaier.ogg",
        LL_M_sidailiangdui:"res/sound/LL/android/man/sidailiangdui.ogg",
        LL_M_T_Line_M:"res/sound/LL/android/man/T_Line_M.ogg",
        LL_M_Three_M:"res/sound/LL/android/man/Three_M.ogg",
        LL_M_Three2_M:"res/sound/LL/android/man/Three2_M.ogg",
        LL_M_wangzha:"res/sound/LL/android/man/wangzha.ogg",
        LL_M_zhadan:"res/sound/LL/android/man/zhadan.ogg",
        LL_M_bujiao:"res/sound/LL/android/man/bujiao.ogg",
        LL_M_buqiang:"res/sound/LL/android/man/buqiang.ogg",
        LL_M_jiaodizhu:"res/sound/LL/android/man/jiaodizhu.ogg",
        LL_M_mingpai:"res/sound/LL/android/man/mingpai.ogg",
        LL_M_qiangdizhu0:"res/sound/LL/android/man/qiangdizhu0.ogg",
        LL_M_qiangdizhu1:"res/sound/LL/android/man/qiangdizhu1.ogg",
        LL_M_qiangdizhu2:"res/sound/LL/android/man/qiangdizhu2.ogg",
        LL_M_sanzhang:"res/sound/LL/android/man/triple_b.ogg",
        LL_F_baojing1:"res/sound/LL/android/female/baojing1.ogg",
        LL_F_baojing2:"res/sound/LL/android/female/baojing2.ogg",
        LL_F_bujiabei:"res/sound/LL/android/female/bujiabei.ogg",
        LL_F_D_Line_F:"res/sound/LL/android/female/D_Line_F.ogg",
        LL_F_bujiao:"res/sound/LL/android/female/bujiao.ogg",
        LL_F_buqiang:"res/sound/LL/android/female/buqiang.ogg",
        LL_F_dan_F_01:"res/sound/LL/android/female/dan_F_01.ogg",
        LL_F_dan_F_02:"res/sound/LL/android/female/dan_F_02.ogg",
        LL_F_dan_F_03:"res/sound/LL/android/female/dan_F_03.ogg",
        LL_F_dan_F_04:"res/sound/LL/android/female/dan_F_04.ogg",
        LL_F_dan_F_05:"res/sound/LL/android/female/dan_F_05.ogg",
        LL_F_dan_F_06:"res/sound/LL/android/female/dan_F_06.ogg",
        LL_F_dan_F_07:"res/sound/LL/android/female/dan_F_07.ogg",
        LL_F_dan_F_08:"res/sound/LL/android/female/dan_F_08.ogg",
        LL_F_dan_F_09:"res/sound/LL/android/female/dan_F_09.ogg",
        LL_F_dan_F_10:"res/sound/LL/android/female/dan_F_10.ogg",
        LL_F_dan_F_11:"res/sound/LL/android/female/dan_F_11.ogg",
        LL_F_dan_F_12:"res/sound/LL/android/female/dan_F_12.ogg",
        LL_F_dan_F_13:"res/sound/LL/android/female/dan_F_13.ogg",
        LL_F_dan_F_14:"res/sound/LL/android/female/dan_F_14.ogg",
        LL_F_dan_F_15:"res/sound/LL/android/female/dan_F_15.ogg",

        LL_F_dani1:"res/sound/LL/android/female/dani1.ogg",
        LL_F_dani2:"res/sound/LL/android/female/dani2.ogg",
        LL_F_dani3:"res/sound/LL/android/female/dani3.ogg",
        LL_F_dui_F_01:"res/sound/LL/android/female/dui_F_01.ogg",
        LL_F_dui_F_02:"res/sound/LL/android/female/dui_F_02.ogg",
        LL_F_dui_F_03:"res/sound/LL/android/female/dui_F_03.ogg",
        LL_F_dui_F_04:"res/sound/LL/android/female/dui_F_04.ogg",
        LL_F_dui_F_05:"res/sound/LL/android/female/dui_F_05.ogg",
        LL_F_dui_F_06:"res/sound/LL/android/female/dui_F_06.ogg",
        LL_F_dui_F_07:"res/sound/LL/android/female/dui_F_07.ogg",
        LL_F_dui_F_08:"res/sound/LL/android/female/dui_F_08.ogg",
        LL_F_dui_F_09:"res/sound/LL/android/female/dui_F_09.ogg",
        LL_F_dui_F_10:"res/sound/LL/android/female/dui_F_10.ogg",
        LL_F_dui_F_11:"res/sound/LL/android/female/dui_F_11.ogg",
        LL_F_dui_F_12:"res/sound/LL/android/female/dui_F_12.ogg",
        LL_F_dui_F_13:"res/sound/LL/android/female/dui_F_13.ogg",
        LL_F_jiabei:"res/sound/LL/android/female/jiabei.ogg",
        LL_F_jiaodizhu:"res/sound/LL/android/female/jiaodizhu.ogg",
        LL_F_mingpai:"res/sound/LL/android/female/mingpai.ogg",
        LL_F_Pass_F_01:"res/sound/LL/android/female/Pass_F_01.ogg",
        LL_F_Pass_F_02:"res/sound/LL/android/female/Pass_F_02.ogg",
        LL_F_Pass_F_03:"res/sound/LL/android/female/Pass_F_03.ogg",
        LL_F_Pass_F_04:"res/sound/LL/android/female/Pass_F_04.ogg",
        LL_F_Plane_F:"res/sound/LL/android/female/Plane_F.ogg",
        LL_F_qiangdizhu0:"res/sound/LL/android/female/qiangdizhu0.ogg",
        LL_F_qiangdizhu1:"res/sound/LL/android/female/qiangdizhu1.ogg",
        LL_F_qiangdizhu2:"res/sound/LL/android/female/qiangdizhu2.ogg",
        LL_F_S_Line_F:"res/sound/LL/android/female/S_Line_F.ogg",
        LL_F_sandaiyi:"res/sound/LL/android/female/sandaiyi.ogg",
        LL_F_sandaiyidui:"res/sound/LL/android/female/sandaiyidui.ogg",
        LL_F_sidaier:"res/sound/LL/android/female/sidaier.ogg",
        LL_F_sidailiangdui:"res/sound/LL/android/female/sidailiangdui.ogg",
        LL_F_superdouble:"res/sound/LL/android/female/superdouble.ogg",
        LL_F_T_Line_F:"res/sound/LL/android/female/T_Line_F.ogg",
        //LL_F_Three_M:"res/sound/LL/android/female/Three_M.ogg",
        //LL_F_Three2_M:"res/sound/LL/android/female/Three2_M.ogg",
        LL_F_wangzha:"res/sound/LL/android/female/wangzha.ogg",
        LL_F_zhadan:"res/sound/LL/android/female/zhadan.ogg",
        LL_F_sanzhang:"res/sound/LL/android/female/triple_0_g.ogg"
    }
}

var g_resources = [];

//common
for (var key in g_mapCommonRes) {
    g_resources.push(g_mapCommonRes[key]);
}

//GD
for (var key in g_mapGDRes) {
    g_resources.push(g_mapGDRes[key]);
}

//sound
for (var key in g_mapAudio) {
    g_resources.push(g_mapAudio[key]);
}

//spine
for (var i = 0,len = loadRes.length; i < len; ++i){
    g_resources.push(loadRes[i]);
}